### ISSUE TITLE
How do i compile? Lots of errors when trying to compile demos

### ISSUE THREAD

**Issue by ferry-creator** [michaelkrzyzaniak/Beat-and-Tempo-Tracking#5]
Hello. I hope it's ok i open this issue, even though it's very noobish. I have experience with a few high level programming languages, and want to get into C. Would love to use this library after watching your amazing demos on YouTube.

I've read a lot about the various C compilers and standards now, and i still can't get it working.  The common wisdom seems to be to use make files for building projects, but some of the demos don't have makefiles. So i'm trying to use the command line to compile.

It's very frustrating for me as a noob, because this library looks sooo cool! But i have no idea how to fix these errors, and i've been googling and searching a lot. Are you able to point me in the right direction? How do you compile?

For the demo "getting_started" i tried using both `gcc main.c` and `clang main.c`. I tried serveral flags, like `-std=90` and others, but none successful. I get the following logged output with `clang`:
```batch
main.c:6:3: warning: implicit declaration of function 'fprintf' is invalid in C99 [-Wimplicit-function-declaration]
  fprintf(stderr, "Yay, an onset was detected %llu samples into the audio stream!\r\n", sample_time);
  ^
main.c:6:3: warning: declaration of built-in function 'fprintf' requires inclusion of the header <stdio.h> [-Wbuiltin-requires-header]
main.c:6:11: error: use of undeclared identifier 'stderr'
  fprintf(stderr, "Yay, an onset was detected %llu samples into the audio stream!\r\n", sample_time);
          ^
main.c:12:3: warning: implicit declaration of function 'fprintf' is invalid in C99 [-Wimplicit-function-declaration]
  fprintf(stderr, "Yay, a beat was detected %llu samples into the audio stream!\r\n", sample_time);
  ^
main.c:12:11: error: use of undeclared identifier 'stderr'
  fprintf(stderr, "Yay, a beat was detected %llu samples into the audio stream!\r\n", sample_time);
          ^
main.c:33:13: error: use of undeclared identifier 'NULL'
  if(btt == NULL){perror("unable to create btt object"); exit(-2);}
            ^
main.c:33:19: warning: implicit declaration of function 'perror' is invalid in C99 [-Wimplicit-function-declaration]
  if(btt == NULL){perror("unable to create btt object"); exit(-2);}
                  ^
main.c:33:58: warning: implicitly declaring library function 'exit' with type 'void (int) __attribute__((noreturn))' [-Wimplicit-function-declaration]
  if(btt == NULL){perror("unable to create btt object"); exit(-2);}
                                                         ^
main.c:33:58: note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'
main.c:36:67: error: use of undeclared identifier 'NULL'
  btt_set_onset_tracking_callback  (btt, onset_detected_callback, NULL);
                                                                  ^
main.c:37:67: error: use of undeclared identifier 'NULL'
  btt_set_beat_tracking_callback   (btt, beat_detected_callback , NULL);
                                                                  ^
5 warnings and 5 errors generated.
```

**Comment by michaelkrzyzaniak** [comment]
These errors are because that example's main.c was missing the lines

#include <stdio.h>
#include <stdlib.h>

which C requires to be able to print things. I have added those lines. The reason they weren't there is that example just passes empty buffers into the beat tracker forever, and is meant more to be read than to be compiled and run.

Nevertheless, if you 'cd' into that folder, you can compile that example with 

gcc *.c ../../src/*.c

You are right that there *should* be makefiles, I just haven't had a chance to make them. For now there are compile commands commented out at the top of each main.c.
