### ISSUE TITLE
Enhance Harmonics is diff from the paper

### ISSUE THREAD

**Issue by deyituo** [michaelkrzyzaniak/Beat-and-Tempo-Tracking#7]
min_lag = (60 * 44100 / 128) / 200 = 103
max_lag = (60 * 44100 / 128) / 50 = 413

As the length of autocorrelation is 1024(2048 in original paper), it seems like that the four_i cannot be added to the self->autocorrelation_real[i], this may cause the partial of the larger I  (257-max_lag) cannot be used, which is unfair for bpm range [50, 200]?

https://github.com/michaelkrzyzaniak/Beat-and-Tempo-Tracking/blob/master/src/BTT.c#L434-L443

**Comment by michaelkrzyzaniak** [comment]
Yes, this is true, it is discussed in the original paper "Streamlined Tempo Estimation Based on
Autocorrelation and Cross-correlation With Pulses" where the authors say "If an index of the impulse train falls outside the OSS frame (for example, at 60 BPM the index can extend as far as 8 seconds), that pulse is omitted from the cross-correlation. This adds a slight penalty to the maximum value of this cross-correlation for tempos less than 71 BPM." The algorithm already has the tendency to double or halve the true tempo, so I'm assuming that whatever was gained by including two_i and four_i outweighs whatever is lost in penalizing slower tempi. You can get back the the specs in the paper with

BTT* btt = btt_new(BTT_SUGGESTED_SPECTRAL_FLUX_STFT_LEN,
                   BTT_SUGGESTED_SPECTRAL_FLUX_STFT_OVERLAP,
                   BTT_SUGGESTED_OSS_FILTER_ORDER,
                   2048,
                   BTT_SUGGESTED_ONSET_THRESHOLD_N,
                   BTT_SUGGESTED_CBSS_LENGTH,
                   BTT_SUGGESTED_SAMPLE_RATE);

btt_set_min_tempo(btt, 50);
btt_set_max_tempo(btt, 210);
