### ISSUE TITLE
"online" demo not working - clicking noises on Mac OS X

### ISSUE THREAD

**Issue by pomplesiegel** [michaelkrzyzaniak/Beat-and-Tempo-Tracking#9]
Hello! This library is very cool. I'm trying to get the online demo working on Mac OS and I have tried on both an Intel 2015 MBP as well as a M1 Macbook Pro. I am running Mac OS 12.6. 

In either case when I run the `online` demo's a.out it does not show any visible BPM detection outputs, and it produces a bunch of audible clicking. It shows the option to scroll through the settings, but I did not find that any of my changes there fixed the behavior. 

Am I doing something wrong? Thank you!

**Comment by michaelkrzyzaniak** [comment]
Hi, yes that is the intended behavior of the demo. It doesn't print out the bpm. If you play music it will click along with the beat. Note however that if you are using your laptop speaker and microphone then it will hear itself clicking and get confused. If you for example use headphones and play recorded music out of your phone's speaker the clicking should match the beat / tempo.

**Comment by pomplesiegel** [comment]
OK, understood, thank you! Trying that now and I notice it is sort of starting and stopping, not consistently hitting a beat for a few different types of music being played.

Is this because various parameters should always be manually adjusted after launching the `online` demo? Is it playing back the moment at which it has beat certainty, or next anticipated beat? 

To be clear, my goal is just to evaluate the algorithm's real-time accuracy in evaluating a tempo for a song as it plays. I don't necessarily need an audio file to be generated - just a fairly real time update (within a second or so) of the current estimated BPM. Is there another demo I should try or a way of looking at the current output? 

"extract_tempo" worked great, but that just shows a single number of the assumed tempo for the whole file. Is there another real-time demo which prints the perceived tempo over time? 

Thank you so much for your help!

**Comment by michaelkrzyzaniak** [comment]
In the extract_tempo demo, you can modify test.c, move

  double tempo = btt_get_tempo_bpm(btt);
  fprintf(stderr, "Tempo of %s is %02f\r\n", argv[1], tempo);

up into the for loop, and it will print the tempo for every AUDIO_BUFFER_SIZE samples.

**Comment by michaelkrzyzaniak** [comment]
I just pushed a new demo called online_print_tempo that should do what you want. It prints the current tempo estimate once per second and does not click.

**Comment by pomplesiegel** [comment]
Wow, this is perfect, exactly what I was looking for!!! Thank you so much. Incredibly helpful and thoughtful of you. Issue 100% closed :)
